### ISSUE TITLE
Приглашаем вас на интервью в наши команду :)

### ISSUE THREAD

**Issue by kezlya** [bloodhgarm/test-nuxt-app#10]

**Comment by DanyDevHouse** [comment]
Добрый день) можно ли по подробнее

**Comment by kezlya** [comment]
Подробную информацию мы высылаем в личку, при условии, если у вас нет каких либо обязанностей перед другой компанией.

**Comment by DanyDevHouse** [comment]
Да вроде нет обязанностей, договоров никаких не заключал) dany945297@mail.ru можете написать сюда
